//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentalCars = new HashSet<RentalCar>();
        }
    
        public int CarId { get; set; }
        public string CarName { get; set; }
        public byte[] CarImage { get; set; }
        public int CarClassId { get; set; }
        public int GearboxTypeId { get; set; }
        public int DriveUnitId { get; set; }
        public decimal RentalPrice { get; set; }
        public string CarAdditionalInfo { get; set; }
        public double AvgConsumption { get; set; }
        public byte Discount { get; set; }
        public int StatusId { get; set; }
    
        public virtual CarClass CarClass { get; set; }
        public virtual DriveUnit DriveUnit { get; set; }
        public virtual GearboxType GearboxType { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalCar> RentalCars { get; set; }
    }
}
