//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsharingEntities : DbContext
    {
        public CarsharingEntities()
            : base("name=CarsharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalService> AdditionalServices { get; set; }
        public virtual DbSet<CarClass> CarClasses { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DriveUnit> DriveUnits { get; set; }
        public virtual DbSet<GearboxType> GearboxTypes { get; set; }
        public virtual DbSet<RentalAddService> RentalAddServices { get; set; }
        public virtual DbSet<RentalCar> RentalCars { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
