//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentalCar()
        {
            this.RentalAddServices = new HashSet<RentalAddService>();
        }
    
        public int RentalCarId { get; set; }
        public int CarId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime RentalStart { get; set; }
        public System.DateTime RentalEnd { get; set; }
        public decimal RentalPrice { get; set; }
        public int StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalAddService> RentalAddServices { get; set; }
        public virtual Status Status { get; set; }
    }
}
