//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAddService
    {
        public int RentalAddServiceId { get; set; }
        public int RentalCarId { get; set; }
        public int AddServiceId { get; set; }
    
        public virtual AdditionalService AdditionalService { get; set; }
        public virtual RentalCar RentalCar { get; set; }
    }
}
